spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crunchy_practice
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://dev-v2glric2u1lmobml.us.auth0.com/'
          audiences: 'crunchy-backend-api-springboot'

server:
  servlet:
    context-path: /api